server:
  port: 8080

spring:
  datasource:
    #url: jdbc:mysql://118.182.96.49:3307/graph?characterEncoding=utf-8&serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/judgements?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: JuPlusNexidao4
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:dataImpl/*Mapper.xml